all: gpp_interpreter

gpp_interpreter:
				yacc -d gpp_interpreter.y -o gpp_interpreter.c 
				lex -o gpp_lexer.c gpp_lexer.l
				cc -g gpp_lexer.c gpp_interpreter.c  -o gpp_interpreter.out -lm
				./gpp_interpreter.out